name: Deployment

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        mkdir -p ${HOME}/.ssh
        echo "${{secrets.SERVER_SSH_KEY}}" > ${HOME}/.ssh/id_rsa
        chmod 700 ${HOME}/.ssh
        chmod 600 ${HOME}/.ssh/*
        eval `ssh-agent -s`
        ssh-add ${HOME}/.ssh/id_rsa

    - name: Sync plugin directory
      run: |
        rsync -chav --delete \
        -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
        ./ ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:${{secrets.REMOTE_TARGET}}
